### ISSUE TITLE
Are Licensing Comments Required (and if so, multiple times)?

### ISSUE THREAD

**Issue by saucier-adobe** [Adobe-Marketing-Cloud/target-atjs-extensions#10]
There are somewhat large licensing comments in the file that are repeated once for each variable. 
1. Do we need to keep them upon deployment?
2. If so, can we make one reference with all the code after?

Thanks,
Lester

**Comment by XDex** [comment]
Hi Lester,
1. Which file would that be?
2. If it's exactly the same license that's being repeated, I don't see why not..

**Comment by saucier-adobe** [comment]
It is in the remote offers extension update. Looks like there are only TWO that are the same. I had thought they all were the same. Thanks. :)

**Comment by XDex** [comment]
Removed redundant WeakMap polyfill license - [tip](https://github.com/Adobe-Marketing-Cloud/target-atjs-extensions/commit/c602c5cb0e80d464cde2b30df0d4f2bf6edb7743)
