### ISSUE TITLE
at.js Remote Offer Code

### ISSUE THREAD

**Issue by kk-adobe** [Adobe-Marketing-Cloud/target-atjs-extensions#19]
Team - 

What code is needed to utilize Remote Offers w/ at.js v0.9.6. 

Assumption: 

- Remote offer plugin is added to the bottom of at.js
- Add polyfill code

Code Snippets: 
/* adobe.target.xt.getRemoteOffersPlugin */  is added to the bottom of the at.js library. 

- Do you have a link to the plugin code snippet? 

Is [this polyfill code](https://raw.githubusercontent.com/Adobe-Marketing-Cloud/target-atjs-extensions/master/remote-offers/dist/at-remote-offers-0.3.0.min.js) still needed w/ at.js v0.9.6, since it has it's own polyfill? 

It would be great to have a wiki with links to code snippets to enable this functionality. The documentation lacks clarity of which code is needed to enable the Remote Offers feature. Also, does implementation vary across at.js versions?

Thanks,
Kollin

**Comment by XDex** [comment]
@kk-adobe We have a Wiki page with a sample snippet here https://github.com/Adobe-Marketing-Cloud/target-atjs-extensions/wiki/Remote-Offers
Regarding the polyfills, these are indeed not needed for at.js v0.9.6, I'll make a release and refactor the extensions and docs to account for this as soon as I get back from my PTO..
On your last question - the implementation should be the same for all at.js versions..

**Comment by XDex** [comment]
@kk-adobe fyi, remote offers extension is now working with at.js > 1.0, after the latest fix in #33
