### ISSUE TITLE
Remote Offers not working with later versions of AT.js (>0.94)

### ISSUE THREAD

**Issue by ittaibaratz** [Adobe-Marketing-Cloud/target-atjs-extensions#26]
Hi there,

The remote offers plugin does not work properly with newer versions of AT.js - Offers are not getting deployed on the page.

I tracked down the issue to the structure of the JSON offer created by the extension. I was able to fix it locally by changing the applyOffers call as follows:

![image](https://user-images.githubusercontent.com/1454683/28340047-3f40ceda-6bc3-11e7-9c50-fcbec84863c3.png)

I am not clear on the gulp build process and so I did not create a pull request - Please let me know if you need more information.

**Comment by artur-ciocanu** [comment]
@XDex when you have a chance could you please take a look.

**Comment by dwright-adobe** [comment]
@XDex , i see that @IttaiB 's fix is necessary to get 0.3.0 working with at.js 1.1.0.  Can you also look at legacy browser support?  0.3.0 references that it uses MO, but haven't the polyfills been removed in the latest at.js versions?

**Comment by XDex** [comment]
@ittaibaratz Fixed in #33 
@dwright-adobe As the polyfills have been removed in the latest at.js versions, MO and WeakMap polyfills are still bundled together with the extension..
