### ISSUE TITLE
Question : React Server Side Rendering

### ISSUE THREAD

**Issue by sabha** [Adobe-Marketing-Cloud/target-atjs-extensions#36]
Do we have any plans to share an API for React Server Side Rendering. Ex - Node can communicate to target/atjs before render to string.

**Comment by garrettmac** [comment]
yeah, please! haha @XDex @vadymus @dwright-adobe @nipunnair. Also what the behavior when you DO do SSR?

**Comment by ramxpa** [comment]
@sabha @garrettmac We now have a node client to support server side rendering 
https://www.npmjs.com/package/@adobe/target-node-client

The node client uses the Target server side delivery API
http://developers.adobetarget.com/api/#server-side-delivery
